### PR TITLE
Process handle is leaked on Windows

### PR DESCRIPTION
**Pull request by acs-godonnell**
Check the return value of various Windows API functions, and call CloseHandle() on the process handle.

### CODE REVIEW

**Comment by acs-godonnell** [comment]
Resolves https://github.com/yvesh/active-windows/issues/5

**Comment by yvesh** [comment]
Thank you for your Pull-Request, going to test it asap. :-)

**Comment by yvesh** [comment]
Works fine. Thank you @acs-godonnell

**Comment by FlisherOfatale** [comment]
I think this issue was forgot in open status?

**Pull request merged**
